server:
  port: 9191

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
dna-validator:
  dna-valid-chars: A,T,C,G
  dna-cant-same-letters: 4
  dna-cant-sequence: 1

